# Continuous Integration Pipeline
name: Continuous Integration Pipeline

on:
  push:
    branches:
      - "*"
      - "!main"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  exit-success:
    needs: [ html, css, javascript, media, backend ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: exit 0

  # superlinter:
  #   name: Lint Code Base
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: Lint Code Base
  #       uses: github/super-linter@v4
  #       env:
  #         VALIDATE_ALL_CODEBASE: false
  #         DEFAULT_BRANCH: main
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo html pipe

  css:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo css pipe

  javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo javascript pipe

  media:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo media pipe
      
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo backend pipe
