# Continuous Integration Pipeline
name: Continuous Integration Pipeline

on:
  push:
    branches: 
      - "*"
      - "!main"
  pull_request:
    branches:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo html pipe

  css:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo css pipe

  javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo javascript pipe

  media:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo media pipe
      
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo backend pipe

  exit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo exit pipe
      - run: exit 0

  default:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.