name: JSDoc Generation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ~/cse110-fa21-group26/source/scripts