name: jsdoc
on: push

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build
      uses: codevise/documentation-js-action@v1
      with:
        input: ../../source/scripts
        output: ./docs

    - name: Install Dependencies
      run: npm install --save-dev jsdoc

    - name: Build 2
      run: jsdoc ~/source/scripts 
