name: Generate JSDocs
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install JSDocs
      run: npm install -g jsdoc

    - name: Build JSDocs
      run: jsdoc /home/runner/work/cse110-fa21-group26/source/scripts
