name: JSDoc Generation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ../source/scripts
          recurse: true
          output_dir: ../source/documentation